config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :subjects 
  resources :students 
  resources :tutors
  resources :appointments 
  resources :reviews 
  resources :student_inboxes 
  resources :student_subjects 

 
  get "/login", to: "students#login", as: "login"

  post "send_the_form_here", to: "students#handle_login"
  delete "/logout", to: "students#logout", as: "logout"

end

app/models/student_subject.rb
class StudentSubject < ApplicationRecord
    belongs_to :student
    belongs_to :subject 

    validates :subject_id, uniqueness: {scope: :student_id}
    
end 

app/controllers/student_subjects_controller.rb
class StudentSubjectsController < ApplicationController
    def new 
        @errors = flash[:errors]
        @student_subject = StudentSubject.new 
    end 

    def create 
        @student_subject = StudentSubject.create(student_subject_params)
        if @student_subject.valid?
        redirect_to student_path(@student_subject.student_id)
        else 
            flash[:errors] = @student_subject.errors.full_messages
            redirect_to new_student_subject_path
        end 
    end 




    private 

    def student_subject_params 
        params.require(:student_subject).permit(:subject_id, :student_id)
    end 
end 

app/views/student_subjects/new.html.erb
<br>
<br>
<br> 
<br>
<br>
<div class="joiners">
<h1> Please Choose your Preferred Subjects </h1>

<% if @errors %>
<%@errors.each do |error|%>
<p style= "color: red; font-size: 24px"> <%= error %></p>
<%end%>
<%end%>


<%= form_for @student_subject, url: student_subjects_path do |f| %>
<%= f.label :subject_id%>
<%= f.collection_select :subject_id, Subject.all, :id, :subject%>
<%= f.hidden_field :student_id, value: @current_student.id %>

<% #f.label :student_id%>
<% #f.collection_select :student_id, Student.all, :id, :first_name %>

<%= f.submit "Set Subject"%>

<%end%>
<br>
<br>

<img src= "https://cms.groupeditors.com/img/2db4717b-8784-4e13-a9f1-2f567fddcbbc.jpg" alt="noooooooo">
</div>