config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :subjects 
  resources :students 
  resources :tutors
  resources :appointments 
  resources :reviews 
  resources :student_inboxes 
  resources :student_subjects 

 
  get "/login", to: "students#login", as: "login"

  post "send_the_form_here", to: "students#handle_login"
  delete "/logout", to: "students#logout", as: "logout"

end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :student_subjects 
    has_many :tutor_subjects
    has_many :students, through: :student_subjects
    has_many :tutors, through: :tutor_subjects
end 

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

    def index 
        @subjects = Subject.all
    end 

    def show 
        @subject = Subject.find(params[:id])
    end 

end 

app/views/subjects/index.html.erb
<br>
<br> 
<br>
<br>
<div class="joiners">
<h1>Subjects Our Tutors Teach </h1>
<div class="subjfont">
    <% @subjects.each do |subject|%>
     <p><ul style="list-style-type:circle;"><%= link_to subject.subject, subject_path(subject.id) %>
    </ul>
    <% end %>
</div>    
</div>

app/views/subjects/show.html.erb
<br>
<br>
<br>
<br>
<br>


<div class="joiners">
<h1> Here are the tutors that teach this Subject! </h1>

<h3> Click on their names to view more information about them! </h3>

<% new_array = [] %>
<%TutorSubject.all.each do |subject|%>
    <% if subject.subject_id == @subject.id%>
    <% new_array << subject.tutor_id %>
    <%end%>

    <%end%>


   <p> <% new_array.each do |tutor_id| %>
    <% @find_tutor = Tutor.all.find(tutor_id)%>
    <%= link_to @find_tutor.first_name, tutor_path(@find_tutor)%> <br></p>
    <%end%>

    </div>
    
    